"""
Django settings for pds2 project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cfau$($ef3ett3btngv2b1a-l&nq-jz!w24-k8n48mee69e#9$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_enumfield',
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pds2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pds2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static_dev'),
]
STATIC_ROOT = os.path.join(BASE_DIR, '..', 'static_live')
STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Jason's settings
CURRENCY_CHOICES = [ ('AUD', 'AUD'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('THB', 'THB'), 
                     ('NZD', 'NZD'), ('IDR', 'IDR')  ]

CURRENCY = { 'AUD': { 'symbol': '$', 'name': 'AU Dollars', 'short': 'AUD' },
         'USD': { 'symbol': '$', 'name': 'US Dollars', 'short': 'USD' },
         'EUR': { 'symbol': u'\u20AC', 'name': 'Euro', 'short': 'EUR' },
         'GBP': { 'symbol': u'\u00A3', 'name': 'Pound Sterling', 'short': 'GBP' },
         'THB': { 'symbol': u'\u0E3F', 'name': 'Thai Baht', 'short': 'THB' },
         'IDR': { 'symbol': u'R', 'name': 'Indonesian Rupiah', 'short': 'IDR' },
         'NZD': { 'symbol': '$', 'name': 'NZ Dollar', 'short': 'NZD' },
}
BRAINTREE_ENVIRONMENT='sandbox'
BRAINTREE_MERCHANT_ID = 'fcvwb46mwhwb98zf'
BRAINTREE_PUBLIC_KEY = 'w29c4bywtqmz2bns'
BRAINTREE_PRIVATE_KEY = 'f6cb66c58185b366bd78b8c37bece1d1'
BRAINTREE_PRODUCTION = False  # We'll need this later to switch between the sandbox and live account
LOGIN_URL = '/admin/login/'